### ISSUE TITLE
Can't install unstable chef-compliance

### ISSUE THREAD

**Issue by alexpop** [chef-cookbooks/chef-ingredient#100]
Using master(0.18.2) chef-ingredient, `chef_ingredient("compliance")` can't find the package to download. See kitchen output below:

```
$ kitchen converge ubuntu14
-----> Starting Kitchen (v1.6.0)
-----> Converging <sweet-ubuntu1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.2...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (12.7.2)
       Transferring files to <sweet-ubuntu1404>
       Starting Chef Client, version 12.7.2
       resolving cookbooks for run list: ["kitchen-omnibus-cc::default", "kitchen-omnibus-cc::setup_ciscat", "kitchen-omnibus-cc::run_ciscat_inspec"]
       Synchronizing Cookbooks:
         - git (4.4.1)
         - build-essential (3.2.0)
         - kitchen-omnibus-cc (0.4.0)
         - yum-epel (0.6.6)
         - yum (3.10.0)
         - chef_handler (1.3.0)
         - windows (1.39.2)
         - chef-ingredient (0.18.2)
         - apt (3.0.0)
         - dmg (2.3.0)
         - seven_zip (2.0.0)
       Compiling Cookbooks...
       Recipe: apt::default
         * bash[apt-get-update at compile time] action run
           - execute "bash"  "/tmp/chef-script20160418-1911-1q9529x"
       [2016-04-18T17:57:33+00:00] WARN: *** action=install, package_version=1.1.1, channel=unstable
         Converging 28 resources
         * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
         * bash[apt-get-update at compile time] action nothing (skipped due to action :nothing)
         * directory[/etc/apt/apt.conf.d] action create (up to date)
         * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create
           - create new file /etc/apt/apt.conf.d/15update-stamp
           - update content in file /etc/apt/apt.conf.d/15update-stamp from none to 174cdb
           --- /etc/apt/apt.conf.d/15update-stamp	2016-04-18 17:57:33.224796293 +0000
           +++ /etc/apt/apt.conf.d/.15update-stamp20160418-1911-5vciaq	2016-04-18 17:57:33.224796293 +0000
           @@ -1 +1,2 @@
           +APT::Update::Post-Invoke-Success {"touch /var/lib/apt/periodic/update-success-stamp 2>/dev/null || true";};
         * execute[apt-get update] action nothing (skipped due to action :nothing)
         * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
         * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
         * execute[apt-get-update-periodic] action run
           - execute apt-get update
         * file[/var/lib/apt/periodic/update-success-stamp] action touch
           - update utime on file /var/lib/apt/periodic/update-success-stamp
         * directory[/var/cache/local] action create
           - create new directory /var/cache/local
           - change mode from '' to '0755'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * directory[/var/cache/local/preseeding] action create
           - create new directory /var/cache/local/preseeding
           - change mode from '' to '0755'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * template[/etc/apt/apt.conf.d/10recommends] action create
           - create new file /etc/apt/apt.conf.d/10recommends
           - update content in file /etc/apt/apt.conf.d/10recommends from none to f41e1d
           --- /etc/apt/apt.conf.d/10recommends	2016-04-18 17:57:40.472418509 +0000
           +++ /etc/apt/apt.conf.d/.10recommends20160418-1911-cd1132	2016-04-18 17:57:40.472418509 +0000
           @@ -1 +1,4 @@
           +# Managed by Chef
           +APT::Install-Recommends "1";
           +APT::Install-Suggests "0";
           - change mode from '' to '0644'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * apt_package[apt-transport-https] action install (up to date)
       Recipe: git::package
         * git_client[default] action install
           * apt_package[default :create git] action install
             - install version 1:1.9.1-1ubuntu0.3 of package git

       Recipe: kitchen-omnibus-cc::setup_compliance
         * chef_ingredient[compliance] action install
         Recipe: <Dynamically Defined Resource>
           * chef_gem[mixlib-install] action install
             - install version ~> 1.0 of package mixlib-install

           ================================================================================
           Error executing action `install` on resource 'chef_ingredient[compliance]'
           ================================================================================

           RuntimeError
           ------------
           No package found for 'compliance' with version '1.1.1' for current platform in 'unstable' channel.
           Check that the package exists.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:95:in `configure_from_channel'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:46:in `configure_package'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:23:in `handle_install'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/kitchen-omnibus-cc/recipes/setup_compliance.rb

            35: chef_ingredient 'compliance' do
            36:   channel json['channel'].to_sym
            37:   version json['package_version']
            38:   ctl_command '/opt/chef-compliance/bin/chef-compliance-ctl'
            39:   notifies :run, "execute[adduser]"
            40:   config <<-EOH
            41: verify_tls false
            42: core.licensed_node_count 77
            43:   EOH
            44:   action actions_array
            45: end
            46:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/kitchen-omnibus-cc/recipes/setup_compliance.rb:35:in `from_file'

           chef_ingredient("compliance") do
             action [:install, :reconfigure]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_ingredient
             cookbook_name "kitchen-omnibus-cc"
             recipe_name "setup_compliance"
             channel :unstable
             version "1.1.1"
             ctl_command "/opt/chef-compliance/bin/chef-compliance-ctl"
             config "verify_tls false\ncore.licensed_node_count 77\n"
             product_name "compliance"
           end

       Running handlers:
       [2016-04-18T17:57:58+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-04-18T17:57:58+00:00] ERROR: Exception handlers complete
       Chef Client failed. 10 resources updated in 34 seconds
       [2016-04-18T17:57:58+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-04-18T17:57:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-04-18T17:57:58+00:00] ERROR: chef_ingredient[compliance] (kitchen-omnibus-cc::setup_compliance line 35) had an error: RuntimeError: No package found for 'compliance' with version '1.1.1' for current platform in 'unstable' channel.
       Check that the package exists.

       [2016-04-18T17:58:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by patrick-wright** [comment]
fixed
