### ISSUE TITLE
Recipe Compile Error fails on include ChefIngredientCookbook::Helpers

### ISSUE THREAD

**Issue by DarrenV79** [chef-cookbooks/chef-ingredient#235]
### Cookbook version
2.3.2

### Chef-client version
14.3.37

### Platform Details
Ubuntu 16.04

### Scenario:
Kitchen 

### Steps to Reproduce:
Trying to deploy a chef server with the chef-server cookbook.  Chef ingredient fails with a compile error.

### Expected Result:
It works

### Actual Result:
================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/automate.rb
       ================================================================================

       NameError
       ---------
       uninitialized constant #<Class:0x0000000004bf43a8>::ChefIngredientCookbook

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/automate.rb:138:in `block in class_from_file'
         /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/automate.rb:137:in `class_from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/automate.rb:

       131:        not_if "automate-ctl list-enterprises --ssh-pub-key-file=/etc/delivery/builder_key.pub | grep -w #{ent}"
       132:        only_if 'automate-ctl status'
       133:      end
       134:    end
       135:  end
       136:
       137:  action_class do
       138>>   include ChefIngredientCookbook::Helpers
       139:  end
       140:

**Comment by DarrenV79** [comment]
Appologies, seems I have to include it now in the berksfile explicitly in order for it to resolve.
