### ISSUE TITLE
chef-client versions prior to 12.1 fail

### ISSUE THREAD

**Issue by foobarbam** [chef-cookbooks/chef-ingredient#24]
See http://jtimberman.housepub.org/blog/2015/03/20/chef-gem-compile-time-compatibility/

```shell
           ================================================================================
           Error executing action `install` on resource 'chef_ingredient[chef-server]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `compile_time' for Chef::Resource::ChefGem
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/helpers.rb:61:in `block in install_mixlib_versioning'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/helpers.rb:59:in `install_mixlib_versioning'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:37:in `block in <class:ChefIngredient>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cms_chef_server/recipes/install.rb
           
            76:   chef_ingredient 'chef-server' do
            77:     package_source  chef_server_pkg
            78:     action          :install
            79:   end
            80: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cms_chef_server/recipes/install.rb:76:in `from_file'
           
           chef_ingredient("chef-server") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_ingredient
             cookbook_name "cms_chef_server"
             recipe_name "install"
             package_source "/sds/local/sceplus/sup/Chef/server/chef-server-core-12.1.2-1.el6.x86_64.rpm"
             product_name "chef-server"
           end
       
       
       Running handlers:
       [2015-08-06T14:32:32+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-08-06T14:32:32+00:00] ERROR: Exception handlers complete
       [2015-08-06T14:32:32+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 18 resources updated in 800.068389056 seconds
       [2015-08-06T14:32:32+00:00] ERROR: chef_ingredient[chef-server] (cms_chef_server::install line 76) had an error: NoMethodError: undefined method `compile_time' for Chef::Resource::ChefGem
       [2015-08-06T14:32:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jtimberman** [comment]
I've noted the Chef version requirement (12.1+) in the README.md. That will be in the next release.
