### ISSUE TITLE
Rails assets are missing for OC-ID

### ISSUE THREAD

**Issue by kplimack** [chef-cookbooks/chef-ingredient#84]
```
==> /var/log/opscode/oc_id/current <==
2016-03-04_23:18:58.68460 I, [2016-03-04T15:18:58.684495 #19133]  INFO -- : Started GET "/id/assets/icons/all.svg" for 17.131.239.16 at 2016-03-04 15:18:58 -0800
2016-03-04_23:18:58.68668 F, [2016-03-04T15:18:58.686625 #19133] FATAL -- :
2016-03-04_23:18:58.68670 ActionController::RoutingError (No route matches [GET] "/id/assets/icons/all.svg"):
2016-03-04_23:18:58.68671   actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
2016-03-04_23:18:58.68671   actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-03-04_23:18:58.68671   railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
2016-03-04_23:18:58.68672   railties (4.2.5.1) lib/rails/rack/logger.rb:22:in `call'
2016-03-04_23:18:58.68672   actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
2016-03-04_23:18:58.68672   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
2016-03-04_23:18:58.68672   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
2016-03-04_23:18:58.68673   activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-03-04_23:18:58.68675   actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
2016-03-04_23:18:58.68676   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
2016-03-04_23:18:58.68677   sentry-raven (0.12.3) lib/raven/integrations/rack.rb:61:in `call'
2016-03-04_23:18:58.68677   railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
2016-03-04_23:18:58.68678   railties (4.2.5.1) lib/rails/application.rb:165:in `call'
2016-03-04_23:18:58.68679   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
2016-03-04_23:18:58.68680   unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
2016-03-04_23:18:58.68680   unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
2016-03-04_23:18:58.68681   unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
2016-03-04_23:18:58.68681   unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
2016-03-04_23:18:58.68681   unicorn-rails (1.1.0) lib/unicorn/rails.rb:24:in `run'
2016-03-04_23:18:58.68681   rack (1.6.4) lib/rack/server.rb:286:in `start'
2016-03-04_23:18:58.68682   railties (4.2.5.1) lib/rails/commands/server.rb:80:in `start'
2016-03-04_23:18:58.68682   railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
2016-03-04_23:18:58.68682   railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
2016-03-04_23:18:58.68682   railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:75:in `server'
2016-03-04_23:18:58.68683   railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2016-03-04_23:18:58.68683   railties (4.2.5.1) lib/rails/commands.rb:17:in `<top (required)>'
2016-03-04_23:18:58.68683   bin/rails:8:in `require'
2016-03-04_23:18:58.68684   bin/rails:8:in `<main>'
2016-03-04_23:18:58.68684
2016-03-04_23:18:58.68684

```

**Comment by wrightp** [comment]
These dependencies are expected to be managed by the recipes, not by chef-ingredient.
